# 项目相关配置
dragon:
  # 名称
  name: my_blog
  # 版本
  version: 1.0.0
  # 版权年份
  copyrightYear: 2019
  # 文件路径
  profile: D:/Temp/profile/
  # 获取ip地址开关
  addressEnabled: true

# 开发环境配置
server:
  # 服务端口
  port: 8088

# 用户配置
user:
  password:
    # 密码错误{maxRetryCount}次锁定10分钟
    maxRetryCount: 8

# Spring配置
spring:
  resources:
    # 静态资源
    static-locations: classpath:/templates,classpath:/static
  thymeleaf:
    mode: HTML
    encoding: utf-8
    # 禁用缓存
    cache: false
  # 资源信息
  messages:
    # 国际化资源文件路径
    basename: i18n/messages
  profiles:
    active: druid

mybatis:
  # 搜索指定包别名
  type-aliases-package: com.dragon.blog.model # 注意：对应实体类的路径
  # 配置mapper的扫描，找到所有的mapper.xml映射文件
  mapper-locations: classpath:mapping/*Mapper.xml #注意：一定要对应mapper映射xml文件的所在路径

# 日志配置
logging:
  level:
    com.dragon: debug
    org.springframework: WARN
    org.spring.springboot.dao: debug
  config: classpath:log4j2-spring.xml

# 分页插件配置
pagehelper:
  helper-dialect: mysql
  reasonable: true
  support-methods-arguments: true
  params: count=countSql

# 登录成功回调地址
blog:
  sso:
    successUrl: /system/index

# shiro配置
shiro:
  paths:
    # 登录地址
    loginUrl: /sso/login
    # 权限认证失败地址
    unauthorizedUrl: /unauth
    # 验证码开关
    captchaEnabled: true
    # 验证码类型 math 数组计算 char 字符
    captchaType: math
  cookie:
    # 设置Cookie的域名 默认空，即当前访问的域名
    domain:
    # 设置cookie的有效访问路径
    path: /
    # 设置HttpOnly属性
    httpOnly: true
    # 设置Cookie的过期时间，天为单位
    maxAge: 30
  session:
    # Session超时时间（默认30分钟）
    expireTime: 30
    # 同步session到数据库的周期（默认1分钟）
    dbSyncPeriod: 1
    # 相隔多久检查一次session的有效性，默认就是10分钟
    validationInterval: 10

# redis配置
redis:
  # redis 地址
  ip: 127.0.0.1
  # redis 端口号
  port: 6379
  # redis 密码
  password: foobared
  # redis 超时时间
  timeout: 1800
  # redis 缓存过期时间
  expiretime: 1000

# 防止XSS攻击
xss:
  # 过滤开关
  enabled: false
  # 排除链接（多个用逗号分隔）
  excludes: /system/notice/*
  # 匹配链接
  urlPatterns: /system/*
